In [1]:
import cv2
import numpy as np

img = cv2.imread('watch.jpg',cv2.IMREAD_COLOR)

In [2]:
img.shape

(168, 300, 3)

In [3]:
px = img[55,55]
print(px)      # original pixels

[29 31 42]


In [4]:
img[55,55] = [255,255,255]

In [5]:
px = img[55,55]
print(px)     # changed pixels

[255 255 255]


In [6]:
px = img[100:150,100:150]
print(px)

[[[ 53  48  57]
  [ 53  48  57]
  [ 54  46  56]
  ...
  [ 36  36  42]
  [ 36  36  42]
  [ 56  56  62]]

 [[ 48  43  52]
  [ 50  45  54]
  [ 53  45  55]
  ...
  [ 36  34  40]
  [ 42  40  46]
  [ 39  37  43]]

 [[ 46  41  50]
  [ 47  42  51]
  [ 51  43  53]
  ...
  [ 33  33  39]
  [ 33  33  39]
  [ 56  56  62]]

 ...

 [[ 25  34  47]
  [ 27  36  49]
  [ 30  39  53]
  ...
  [105 114 128]
  [106 114 131]
  [106 114 131]]

 [[ 27  36  50]
  [ 26  35  49]
  [ 26  35  49]
  ...
  [ 96 110 129]
  [105 116 138]
  [109 120 142]]

 [[ 27  36  50]
  [ 25  34  48]
  [ 25  34  48]
  ...
  [101 114 136]
  [100 112 136]
  [107 117 141]]]


In [7]:
img[100:150,100:150] = [255,255,255]

In [8]:
print(img.shape)
print(img.size)
print(img.dtype)

(168, 300, 3)
151200
uint8


In [9]:
# Getting ROI:Region of Interest
import cv2
import numpy as np

img = cv2.imread('watch.jpg',cv2.IMREAD_COLOR)
watch_face = img[37:111,107:194]
img[0:74,0:87] = watch_face

cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()